source "http://rubygems.org"

gem 'cucumber', '~> 6.1'
gem 'capybara', '~> 3.35', '>= 3.35.3'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7'
gem 'rspec', '~> 3.10'
gem 'site_prism', '~> 3.7', '>= 3.7.1'
gem 'webdrivers'